version: '3.1'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: shared_db
      POSTGRES_USER: quants_db
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  discovery-server:
    build:
      context: ./discovery
    ports:
      - "8761:8761"
    depends_on:
      - config-server
      - postgres
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/

  api-gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  match-management:
    build:
      context: ./match-management
    ports:
      - "8086:8086"
    depends_on:
      - discovery-server
      - config-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shared_db
      - SPRING_DATASOURCE_USERNAME=quants_db
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  ms-user-management:
    build:
      context: ./ms-user-management
    ports:
      - "8085:8085"
    depends_on:
      - discovery-server
      - config-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shared_db
      - SPRING_DATASOURCE_USERNAME=quants_db
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

volumes:
  postgres_data:
